apiVersion: apps/v1
# Тип ресурса.
kind: Deployment
metadata:
  # Имя этого Deployment.
  name: werf-guide-app
spec:
  # Кол-во реплик этого Deployment.
  replicas: 1
  selector:
    matchLabels:
      # По этому лейблу Deployment находит обслуживаемые им Pods.
      app: werf-guide-app
  # Описание шаблона, на основе которого создаются Pods для этого Deployment.
  template:
    metadata:
      labels:
        # Лейблы создаваемых Pods.
        app: werf-guide-app
    spec:
      imagePullSecrets:
      # Имя секрета с Docker credentials для доступа к container registry.
      - name: registrysecret
      containers:
      # Имя первого контейнера.
      - name: app
        # Имя и тег образа контейнера.
        image: {{ .Values.werf.image.app }}
        # Основная команда контейнера, начнёт выполняться при его запуске.
        command: ["/app/start.sh"]
        # Порт, на котором будет слушать запускаемое приложение.
        ports:
        - containerPort: 8000
